apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Your email. Replace it!
    email: USER_EMAIL
    server: https://acme-v01.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - dns01:
          clouddns:
            # The ID of your GCP project. Replace it!
            project: GOOGLE_CLOUD_PROJECT
            serviceAccountSecretRef:
              name: clouddns-dnssac-secret
              key: dnssac_key.json