apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  loadBalancerIP: EXTERNAL_IP
  selector:
    app: grpcexample
  ports:
    - name: grpclb
      protocol: TCP
      port: 50051 # port facing the internet
      targetPort: 50052 # point to the Endpoints proxy in our pods